name: sokuma_ui
description: SOKu-ma の個人開発 Flutter アプリで共通利用するデザインシステム。
version: 0.1.0
repository: https://github.com/SOKu-ma/sokuma_ui
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
